---
- import_tasks: add-repo-4-debian-apt.yml
- import_tasks: add-repo-4-redhat-yum.yml

- name: Add repo VirtualBox 4 CentOS 8\Fedora
  when: 
    - ansible_os_family == 'RedHat'
    - ansible_pkg_mgr == 'dnf'
  become: yes
  yum_repository:
    description: Oracle Linux / RHEL / CentOS-$releasever / $basearch - VirtualBox
    file: virtualbox
    name: virtualbox
    baseurl: '{{ http_or_https }}://download.virtualbox.org/virtualbox/rpm/rhel/$releasever/$basearch'
    gpgkey: "{{ virtualbox_repo_rpm_key }}"
    enabled: yes
    gpgcheck: yes
    state: present
  tags:
    - linux
    - fedora
    - virtualbox
    - repo
    - config

# На 27-02-2022 всё ещё непонятно как добавлять репу, если Leap 15.3, а репа - 15.0. Городить дикие костыли не хочется, так что suse снова пролетает.
# # https://ru.opensuse.org/SDB:%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0_VirtualBox
# # http://download.virtualbox.org/virtualbox/rpm/opensuse/virtualbox.repo
# - name: Add repo VirtualBox 4 OpenSUSE Tumbleweed
#   when:
#     - ansible_os_family == 'Suse'
#     - ansible_distribution != 'openSUSE Tumbleweed'
#   become: yes
#   block:
#     - zypper_repository:
#         description: VirtualBox for openSUSE $releasever - $basearch
#         repo: '{{ http_or_https }}://download.virtualbox.org/virtualbox/rpm/opensuse/$releasever/$basearch'
#         name: virtualbox
#         auto_import_keys: yes
#         state: present
#   tags:
#     - linux
#     - suse
#     - opensuse
#     - virtualbox
#     - repo
#     - config
