---
- name: Add repo GPG key
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: yes
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "{{ virtualbox_repo_deb_key }}"
  tags:
    - linux
    - ubuntu
    - virtualbox
    - repo
    - key
    - gpg

- name: Add repo VirtualBox 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64] {{ http_or_https }}://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib non-free'
    state: present
    filename: virtualbox
  tags:
    - linux
    - ubuntu
    - virtualbox
    - repo
    - add
