---
- name: Add repo VirtualBox 4 CentOS\RHEL
  when:
    - ansible_os_family == 'RedHat'
    - ansible_pkg_mgr == 'yum'
  become: yes
  yum_repository:
    file: virtualbox
    name: virtualbox
    description: Oracle Linux / RHEL / CentOS-$releasever / $basearch - VirtualBox
    baseurl: '{{ http_or_https }}://download.virtualbox.org/virtualbox/rpm/el/$releasever/$basearch'
    gpgkey: "{{ virtualbox_repo_rpm_key }}"
    enabled: yes
    gpgcheck: yes
    state: present
  tags:
    - linux
    - centos
    - virtualbox
    - repo
    - config
