---
- name: Install\Update VirtualBox 4 Windows
  when:
    - ansible_os_family == 'Windows'
    - ansible_env.PROCESSOR_ARCHITECTURE == 'AMD64'
    - virtualbox_full_available_version_fact != virtualbox_exe_version_fact
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  block:
    - win_package:
        path: '{{ virtualbox_windows_local_download_path }}\{{ virtualbox_installer_file_fact }}'
        product_id: 'Oracle VM VirtualBox {{ virtualbox_available_version_fact }}'
        creates_path: '{{ virtualbox_win_path_to_exe_fact }}'
        arguments:
          - --silent
    - win_path:
        elements:
          - '{{ ansible_env.ProgramFiles }}\Oracle\VirtualBox'
          - '%VBOX_MSI_INSTALL_PATH%'
        state: present
    - win_file:
        path: '{{ virtualbox_windows_local_download_path }}'
        state: absent

#---

- name: Install VirtualBox 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
    # - ansible_pkg_mgr == 'apt'
    # - ansible_architecture == 'x86_64'
  become: yes
  package:
    name: virtualbox-{{ virtualbox_available_major_and_minor_version_fact }}
    state: present
  notify:
    - run-vboxconfig

#---

- name: Install VirtualBox 4 enterprise RHEL-like
  when:
    - ansible_os_family == 'RedHat'
  become: yes
  block:
    - package:
        name:
          - gcc
          - kernel-devel
          - kernel-headers
          - make
          - perl
          - elfutils-libelf-devel
          - VirtualBox-{{ virtualbox_available_major_and_minor_version_fact }}
        state: present
      register: vbox_install
    - command: vboxconfig
      when: vbox_install.changed
  # notify:
  #   - run-vboxconfig

#---

- name: Install VirtualBox 4 openSUSE
  when:
    - ansible_os_family == 'Suse'
  become: yes
  package:
    name:
      - virtualbox
    state: present
  notify:
    - run-vboxconfig
