---
- import_tasks: update-cache.yml
  
- import_tasks: get-virtualbox-version-and-set-facts.yml

- import_tasks: install-dependencies.yml

- import_tasks: download-virtualbox.yml
  when:
    - ansible_os_family == 'Windows'
    - virtualbox_exe_version_fact != virtualbox_full_available_version_fact

- import_tasks: add-repo-virtualbox.yml

- import_tasks: install-virtualbox.yml

- import_tasks: download-extensionpack.yml

- import_tasks: install-extensionpack.yml
